/*
 * Please do not edit this file.
 * It was generated using rpcgen.
 */

#ifndef _RPC_XFILE_H_RPCGEN
#define _RPC_XFILE_H_RPCGEN

#include <rpc/rpc.h>


#ifdef __cplusplus
extern "C" {
#endif

#define USERLENGTH 32
#define STATUSLENGTH 3
#define LINELENGTH 128
#define NUM_USERS 4
#define MAX_ELEMENTS 5

struct Utente {
	char nome[USERLENGTH];
};
typedef struct Utente Utente;

struct Stanza {
	char nome[LINELENGTH];
	char stato[STATUSLENGTH];
	Utente utenti[NUM_USERS];
};
typedef struct Stanza Stanza;

typedef Utente Input1;

struct Input2 {
	char nome[LINELENGTH];
};
typedef struct Input2 Input2;

struct Output1 {
	int esito;
	Stanza stanzeLiberate[MAX_ELEMENTS];
};
typedef struct Output1 Output1;

#define RPCPROG 0x20000015
#define RPCVERS 1

#if defined(__STDC__) || defined(__cplusplus)
#define ELIMINA_UTENTE 1
extern  Output1 * elimina_utente_1(Input1 *, CLIENT *);
extern  Output1 * elimina_utente_1_svc(Input1 *, struct svc_req *);
#define ELIMINA_STANZA 2
extern  int * elimina_stanza_1(Input2 *, CLIENT *);
extern  int * elimina_stanza_1_svc(Input2 *, struct svc_req *);
extern int rpcprog_1_freeresult (SVCXPRT *, xdrproc_t, caddr_t);

#else /* K&R C */
#define ELIMINA_UTENTE 1
extern  Output1 * elimina_utente_1();
extern  Output1 * elimina_utente_1_svc();
#define ELIMINA_STANZA 2
extern  int * elimina_stanza_1();
extern  int * elimina_stanza_1_svc();
extern int rpcprog_1_freeresult ();
#endif /* K&R C */

/* the xdr functions */

#if defined(__STDC__) || defined(__cplusplus)
extern  bool_t xdr_Utente (XDR *, Utente*);
extern  bool_t xdr_Stanza (XDR *, Stanza*);
extern  bool_t xdr_Input1 (XDR *, Input1*);
extern  bool_t xdr_Input2 (XDR *, Input2*);
extern  bool_t xdr_Output1 (XDR *, Output1*);

#else /* K&R C */
extern bool_t xdr_Utente ();
extern bool_t xdr_Stanza ();
extern bool_t xdr_Input1 ();
extern bool_t xdr_Input2 ();
extern bool_t xdr_Output1 ();

#endif /* K&R C */

#ifdef __cplusplus
}
#endif

#endif /* !_RPC_XFILE_H_RPCGEN */
