/*
 * Please do not edit this file.
 * It was generated using rpcgen.
 */

#include "RPC_xFile.h"

bool_t
xdr_Utente (XDR *xdrs, Utente *objp)
{
	register int32_t *buf;

	int i;
	 if (!xdr_vector (xdrs, (char *)objp->nome, USERLENGTH,
		sizeof (char), (xdrproc_t) xdr_char))
		 return FALSE;
	return TRUE;
}

bool_t
xdr_Stanza (XDR *xdrs, Stanza *objp)
{
	register int32_t *buf;

	int i;
	 if (!xdr_vector (xdrs, (char *)objp->nome, LINELENGTH,
		sizeof (char), (xdrproc_t) xdr_char))
		 return FALSE;
	 if (!xdr_vector (xdrs, (char *)objp->stato, STATUSLENGTH,
		sizeof (char), (xdrproc_t) xdr_char))
		 return FALSE;
	 if (!xdr_vector (xdrs, (char *)objp->utenti, NUM_USERS,
		sizeof (Utente), (xdrproc_t) xdr_Utente))
		 return FALSE;
	return TRUE;
}

bool_t
xdr_Input1 (XDR *xdrs, Input1 *objp)
{
	register int32_t *buf;

	 if (!xdr_Utente (xdrs, objp))
		 return FALSE;
	return TRUE;
}

bool_t
xdr_Input2 (XDR *xdrs, Input2 *objp)
{
	register int32_t *buf;

	int i;
	 if (!xdr_vector (xdrs, (char *)objp->nome, LINELENGTH,
		sizeof (char), (xdrproc_t) xdr_char))
		 return FALSE;
	return TRUE;
}

bool_t
xdr_Output1 (XDR *xdrs, Output1 *objp)
{
	register int32_t *buf;

	int i;
	 if (!xdr_int (xdrs, &objp->esito))
		 return FALSE;
	 if (!xdr_vector (xdrs, (char *)objp->stanzeLiberate, MAX_ELEMENTS,
		sizeof (Stanza), (xdrproc_t) xdr_Stanza))
		 return FALSE;
	return TRUE;
}
